### ISSUE TITLE
Uploading to Maven central?

### ISSUE THREAD

**Issue by qin** [BrightTag/kafkameter#10]
Hi Cody, would you have the interest to upload this module into Maven central, or can I somehow folk this repo and upload to Maven central? I'm sure many folks would love to be able to rely on this module through Maven.

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by codyaray** [comment]
Hi qin,

You're welcome to build and upload. I no longer work at BrightTag but I'd love to see people use this little tool. It was a nice help when we were using it. :)

-Cody

**Comment by qin** [comment]
Great, will do~

**Comment by daluu** [comment]
Just an FYI to the casual reader coming across this item:

the maven repo/info: https://mvnrepository.com/artifact/com.github.qin/kafkameter

the github repo for the maven artifact: https://github.com/qin/kafkameter
