### ISSUE TITLE
Need SSL connection to kafka

### ISSUE THREAD

**Issue by rammulay** [BrightTag/kafkameter#11]
Hi - I am trying to use kafkameter to setup a test through JMeter but I need a secure connection to kafka. I am assuming I will have to write my own class like KafkaProducerSampler and set the properties needed to make a secure connection to kafka such as 'ssl.keystore.location', 'ssl.keystore.password', 'ssl.truststore.location', 'ssl.truststore.password' and 'security.protocol'? What else do I need? Please advise - thanks!

**Comment by codyaray** [comment]
That sounds accurate. You could probably just fork this repo, make the changes (and test them!), and send a PR. If it works we'll be happy to merge. :)

**Comment by rammulay** [comment]
I had to upgrade to the kafka version to 0.9.0.1 to get SSL to work with kafkameter. I get permission denied when I try and fork your repo. I think that has something to do with my end of things...so I will figure that out. With the upgrade in version, do you still want the PR?

**Comment by rammulay** [comment]
Created https://github.com/BrightTag/kafkameter/pull/12 for SSL capability.
