### ISSUE TITLE
Logs available?

### ISSUE THREAD

**Issue by tiagokos** [BrightTag/kafkameter#18]
Hello,

I am trying to send messages to a Kafka broker installed in another machine but can't see much when messages fail. Is there any logging enabled where I could check its status?

Thanks,
Tiago

**Comment by codyaray** [comment]
You should be able to see exceptions/failures inside the JMeter gui. The
kafkameter plugin sets any exception inside the result itself:

https://github.com/BrightTag/kafkameter/blob/master/src/main/java/co/signal/kafkameter/KafkaProducerSampler.java#L266
