### ISSUE TITLE
Jmeter kafkameter doesn't close connections

### ISSUE THREAD

**Issue by kotavi** [BrightTag/kafkameter#2]
Hello!
I have test scenario for distributed mode where I run my test on several VMs. I noticed that after test was finished and on each VM was message "Finished the test on host 192.168.9.8 @ Fri Apr 24 18:30:32 UTC 2015 (1429900232494)" I still had hanging connections on the test VMs and VMs under the testing. 
On one kafka node:
netstat -nap | wc -l
7459
Could you tell me how it can be handled? 

Thanks

**Comment by codyaray** [comment]
Hi @kotavi, 

I've just pushed a change that I think will fix this issue. We weren't properly closing the Kafka producer after the test ended. If you could test this and let me know if it works, that'd be great. :)

-Cody

**Comment by kotavi** [comment]
Thanks!
It worked, I measured number of connections before and after the test (not stopping the servers)
  node    before   after
kafka5    2848  2846
kafka4    8146  8145
kafka3    1512  1509
kafka2     241   240
kafka1     9711  9707

**Comment by codyaray** [comment]
Awesome. Marking as closed.
