### ISSUE TITLE
Null Pointer Exception in KafkaProcucerSampler

### ISSUE THREAD

**Issue by ashish-khatkar** [BrightTag/kafkameter#21]
I am using Kafkameter to ingest events into kafka topic with jmeter. I am getting null pointer exception at line 188 (producer.send). I changed the kafka broker string to my kafka cluster brokers and also updated the topic to which I wanted to push. Is there any other configuration that I might be missing ? Seems like producer is not being created. Can it be due to Kafka version mismatch between cluster and Kafka client api ?

**Comment by codyaray** [comment]
Can you share what the fix was so others can learn from it?
