### ISSUE TITLE
SSL variable go away as soon as I save or run

### ISSUE THREAD

**Issue by santiagomoneta** [BrightTag/kafkameter#25]
Hello I followed the steps and I notice that when I add the Java request with the kafkaproducerSampler class I get the required values which I replace with the ones I need, so fa so good..

The problem is when I want to add the ssl variables... as soon I do that and save or run teh script, those variables go away and only the defaults stay (with the updated values)..

Can the SSL variables be added on the root element ?

Thanks!
added one extra variable:
![2020-03-03_12-55-15](https://user-images.githubusercontent.com/8931496/75793740-8f3a0d00-5d4e-11ea-8b47-038d41882a2b.jpg)

As soon I run or save, it goes away.
![2020-03-03_12-55-36](https://user-images.githubusercontent.com/8931496/75793752-93fec100-5d4e-11ea-93a1-3d1de1a55338.jpg)

**Comment by codyaray** [comment]
I would try adding the extra parameters you need directly to the sampler class: https://github.com/BrightTag/kafkameter/blob/52908a6871d9aa33a88e2f02c664429e4944afda/src/main/java/co/signal/kafkameter/KafkaProducerSampler.java#L131

(Sorry I haven't touched this in a million years)

PS - I'm from Arkansas, so very curious how you're topic came to be named `arkansas-...` :)

**Comment by santiagomoneta** [comment]
Thanks for the reply!

I will try that and get back to you... apparently is a JMeter known issue (https://bz.apache.org/bugzilla/show_bug.cgi?id=42867)

As for the name... Heroku choose it randomly lol!

**Comment by santiagomoneta** [comment]
in this case, the parameters I need are already there, the SSL config.. but it goes away as soon I run or save... I was talking more like making another class that includes the SSL parameters by default.

**Comment by santiagomoneta** [comment]
Kinda fix it... I edited the file "KafkaProducerSampler.java" and moved the line #164 "defaultParameters.addArgument(PARAMETER_KAFKA_USE_SSL, "${PARAMETER_KAFKA_USE_SSL}");" right below #154 (defaultParameters.addArgument(PARAMETER_KAFKA_BROKERS, "${PARAMETER_KAFKA_BROKERS}");) saved and compiled (cmd "mvn package") and then replacede the new jar with the one in the jmeter lib/ext folder and viola!... all parameters are there now!.. why? no idea!
![2020-03-05_11-51-40](https://user-images.githubusercontent.com/8931496/75993612-837a5200-5ed8-11ea-8c1d-8619d80a08ef.jpg)
