### ISSUE TITLE
Kafka consumer sampler?

### ISSUE THREAD

**Issue by daluu** [BrightTag/kafkameter#3]
Hi, thanks for making this plugin, and good thing I just need producer load generation for the moment.

It seems those who tackle load testing that involves kafka focus on the producer side so far.

Perhaps, there may be cases where we want to stress test the consumer scalability of a kafka deployment. Any thoughts to adding a consumer sampler in the future? Maybe just supporting a simple consumer, high level consumer, or both.

Similar to this other project request:

https://github.com/mnogu/gatling-kafka/issues/1

I kind of imagine that the consumer sampler would behave like the HTTP response portion of HTTP request sampler where we get back a response to validate with a response assertion component or other asserters or post-processors. Although the user may choose not to do any content validations and just stress system with # of consumers (as JMeter samplers) running against kafka.

Although consumers generally run continuously until stopped, not sure how to deploy that with JMeter. One option could be to mimic the kafka-console-consumer.sh (and simple consumer version) option of consuming a max of 1 message. In which case the JMeter kafka consumer sampler would only fetch a single message and return the response for validation and/or post-processing. To continuously consume more messages, the user would construct JMeter test plan that utilized loops, etc. to continuously call/run the consumer sampler.

**Comment by codyaray** [comment]
Hi @daluu 

The original intent behind KafkaMeter wasn't for stress testing Kafka itself. That's more of a side effect. The goal was to stress test our downstream components that consume from Kafka. It builds on JMeter to simulate a number of users taking certain actions which eventually result in messages being added to Kafka for consumption by your own applications. Said differently, it generates synthetic messages to Kafka which serves as load for an application that's driven by Kafka messages.

This is why its not a great fit for stress testing Kafka itself; its not just what it was designed to do. Realistically, if you want a JMeter component which reads from Kafka, this isn't going to be a huge help. But it could serve as a good clean model for developing JMeter plugins. 

Does that make more sense?

**Comment by daluu** [comment]
Yes, thanks for the clarification. I was just thinking that perhaps more consumers can also affect the overall system (from kafka dependency), and using a tool like JMeter (and this) would be more effective to exercise that kind of scenario than trying to spin up more downstream consumer components in our system for example (say to simulate what would happen if we did scale up our consumers more in our system). But then again, I suppose issues are more likely to stem at the producer side than consumer side in terms of load and scalability.
