### ISSUE TITLE
Publish compiled extension to maven repo and Github releases?

### ISSUE THREAD

**Issue by daluu** [BrightTag/kafkameter#5]
Although a trivial matter for one to compile oneself, they are still extra steps.

Excluding one's need to typically create custom versions of a SyntheticLoadGenerator, the extension itself is general enough to just compile without any changes.

Have you thought to publish a compiled version to maven so others can easily pull it into their maven projects using JMeter? And/or publish to Github releases for download skipping need to compile ourselves?

By the way, there is a JMeter maven plugin:

https://github.com/jmeter-maven-plugin/jmeter-maven-plugin

**Comment by codyaray** [comment]
Patches welcome. :)

**Comment by daluu** [comment]
For the casual reader coming across this item, see issue #10.
