### ISSUE TITLE
Compiling and running - version dependencies for JMeter, Kafka, Guava, etc.

### ISSUE THREAD

**Issue by daluu** [BrightTag/kafkameter#6]
Hi, it may be nice to add to the readme, the info regarding dependencies during compilation and running the extension. And/or this issue could be use to track dependency issues when compiling and running against specific versions of JMeter, Kafka, maven, etc.

I observe the following:

Using JMeter 2.13 (I didn't test JMeter 2.11 that the default compilation is against) on my Mac running Java 1.8.0_45 (64-bit), using the default config from this repo during compilation, when I run JMeter with the plugin added, it fails to launch with the following error below. I used Maven 3.3.3.

An error occurred: class com.google.common.collect.EmptyImmutableList overrides final method toArray.([Ljava/lang/Object;)[Ljava/lang/Object;

I looked that up and found this related post

https://code.google.com/p/guava-libraries/issues/detail?id=1539

So I tried switching to compile against Guava 15 in the POM, that fixed the startup problem. I don't use Guava (not aware what other software I have on my system that might use it, to result in conflicting Guava classpath issues).

Also, before I fixed the issue with the Guava tweak, I tried compiling against JMeter 2.13 instead of 2.11. That resulted in this compile error from maven:

[WARNING] The POM for commons-math3:commons-math3:jar:3.4.1 is missing, no dependency information available
[WARNING] The POM for commons-pool2:commons-pool2:jar:2.3 is missing, no dependency information available

[ERROR] Failed to execute goal on project kafkameter: Could not resolve dependencies for project kafkameter:kafkameter:jar:0.2.0: The following artifacts could not be resolved: commons-math3:commons-math3:jar:3.4.1, commons-pool2:commons-pool2:jar:2.3: Failure to find commons-math3:commons-math3:jar:3.4.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Would the fix here be doing the exclusion and transitive dependency stuff? Or locally provide the missing JAR dependencies?

Last, I see the default config is to compile for Kafka 0.8.0. I wonder if there will be issues trying to compile for more recent versions of kafka.

**Comment by codyaray** [comment]
Good points. A few things that should've been specified explicitly in the POM. We only used Java 7 and Maven 2. (We only upgraded to Java 8 recently and have some old plugin dependencies in other components for Maven 2 still, so we're way behind on that upgrade.) 

As far as the library dependency versions, the config that's in the POM is the only config we tested against. We hadn't upgraded from Kafka 0.8.0 at the time and exclusively used JMeter 2.11.

**If you want to update the README with instructions for other working configurations, please send a pull request and I'll get it merged in.**

-Cody
